// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMdTRbUd8nHoaGAl_5A4cpy9FZAGeMVlg',
    appId: '1:350983901000:web:0e86e35a8ea07c4a8aad7d',
    messagingSenderId: '350983901000',
    projectId: 'snehaemart',
    authDomain: 'snehaemart.firebaseapp.com',
    storageBucket: 'snehaemart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3u5TE7vTpv46sJRopvKAZMwU9q8vJd04',
    appId: '1:350983901000:ios:c5551efa95e347068aad7d',
    messagingSenderId: '350983901000',
    projectId: 'snehaemart',
    storageBucket: 'snehaemart.appspot.com',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3u5TE7vTpv46sJRopvKAZMwU9q8vJd04',
    appId: '1:350983901000:ios:c5551efa95e347068aad7d',
    messagingSenderId: '350983901000',
    projectId: 'snehaemart',
    storageBucket: 'snehaemart.appspot.com',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMdTRbUd8nHoaGAl_5A4cpy9FZAGeMVlg',
    appId: '1:350983901000:web:709b948264f55f968aad7d',
    messagingSenderId: '350983901000',
    projectId: 'snehaemart',
    authDomain: 'snehaemart.firebaseapp.com',
    storageBucket: 'snehaemart.appspot.com',
  );
}
